
library("here")
library("sessioninfo")


outdir <- "smokingMouse_files"
pkgname <- "smokingMouse"


meta <- data.frame(
  Title = c(
    "rse_gene_mouse_RNAseq_nic-smo",
    "rse_tx_mouse_RNAseq_nic-smo",
    "rse_jx_mouse_RNAseq_nic-smo",
    "rse_exon_mouse_RNAseq_nic-smo",
    "de_genes_prenatal_human_brain_smoking",
    "de_genes_adult_human_brain_smoking"
  ),
  Description = c(
    "RangedSummarizedExperiment of bulk RNA-seq data from mouse brain and blood at the gene level, generated by the Lieber Institute for Brain Development (LIBD) and available through the smokingMouse Bioconductor package.",
    "RangedSummarizedExperiment of bulk RNA-seq data from mouse brain and blood at the transcript (tx) level, generated by the Lieber Institute for Brain Development (LIBD) and available through the smokingMouse Bioconductor package.",
    "RangedSummarizedExperiment of bulk RNA-seq data from mouse brain and blood at the exon-exon junction (jx) level, generated by the Lieber Institute for Brain Development (LIBD) and available through the smokingMouse Bioconductor package.",
    "RangedSummarizedExperiment of bulk RNA-seq data from mouse brain and blood at the exon level, generated by the Lieber Institute for Brain Development (LIBD) and available through the smokingMouse Bioconductor package.",
    "GRanges with the information of the differentialy expressed genes (DEG) in smoking human prenatal brain, generated by Semick, S.A. et al. (2018), Mol Psychiatry, DOI: https://doi.org/10.1038/s41380-018-0223-1, obtained from https://github.com/LieberInstitute/Smoking_DLPFC_Devel",
    "GRanges with the information of the differentialy expressed genes (DEG) in smoking human adult brain, generated by Semick, S.A. et al. (2018), Mol Psychiatry, DOI: https://doi.org/10.1038/s41380-018-0223-1, obtained from https://github.com/LieberInstitute/Smoking_DLPFC_Devel."
  ),
  BiocVersion = "3.17",
  Genome = rep(c("GRCm38", "GRCh37"), c(4,2)),
  SourceType = "GTF",
  SourceUrl = "https://bioconductor.org/packages/smokingMouse",
  SourceVersion = "Feb 28 2023",
  Species = rep(c("Mus musculus", "Homo sapiens"), c(4,2)),
  TaxonomyId = rep(c("10090", "9606"),c(4,2)),
  Coordinate_1_based = TRUE,
  DataProvider = "Lieber Institute for Brain Development (LIBD)",
  Maintainer = "Daianna Gonzalez-Padilla <glezdaianna@gmail.com>",
  RDataClass = rep(c("RangedSummarizedExperiment", "GenomicRanges"), c(4,2)),
  DispatchClass = "Rda",
  RDataPath = file.path(
    pkgname,
    outdir,
    c(
      "rse_gene_mouse_RNAseq_nic-smo.Rdata",
      "rse_tx_mouse_RNAseq_nic-smo.Rdata",
      "rse_jx_mouse_RNAseq_nic-smo.Rdata",
      "rse_exon_mouse_RNAseq_nic-smo.Rdata",
      "de_genes_prenatal_human_brain_smoking.Rdata",
      "de_genes_adult_human_brain_smoking.Rdata"
    )
  ),
  Tags = "smokingMouse:LIBD:mouse:smoking:nicotine",
  row.names = NULL,
  stringsAsFactors = FALSE
)

write.csv(
  meta,
  file = here::here("inst", "extdata", "metadata.csv"),
  row.names = FALSE
)

## Check
if (FALSE) {
  AnnotationHubData::makeAnnotationHubMetadata(here::here(), fileName = "metadata.csv")
}





## Reproducibility information
print("Reproducibility information:")
Sys.time()
proc.time()
options(width = 120)
session_info()

# setting  value
# version  R version 4.2.2 (2022-10-31)
# os       macOS Monterey 12.5.1
# system   aarch64, darwin20
# ui       RStudio
# language (EN)
# collate  en_US.UTF-8
# ctype    en_US.UTF-8
# tz       America/Mexico_City
# date     2023-02-28
# rstudio  2022.12.0+353 Elsbeth Geranium (desktop)
# pandoc   NA
