
library("here")
library("sessioninfo")


outdir <- "inst/extdata"
pkgname <- "smokingMouse"


meta <- data.frame(
  Title = c(
    ## Raw data
    "rse_gene_smoking_mouse_n208",
    "rse_tx_smoking_mouse_n208",
    "rse_jx_smoking_mouse_n208",
    "rse_exon_smoking_mouse_n208",
    "fetalGene",
    "adultGene",
    "Maternal_Smoking_pheno"
  ),
  Description = c(
    "RangedSummarizedExperiment of bulk RNA-seq data from mouse brain and blood at the gene level, generated by the LIBD and available through the smokingMouse Bioconductor package.",
    "RangedSummarizedExperiment of bulk RNA-seq data from mouse brain and blood at the tx level, generated by the LIBD and available through the smokingMouse Bioconductor package.",
    "RangedSummarizedExperiment of bulk RNA-seq data from mouse brain and blood at the jx level, generated by the LIBD and available through the smokingMouse Bioconductor package.",
    "RangedSummarizedExperiment of bulk RNA-seq data from mouse brain and blood at the exon level, generated by the LIBD and available through the smokingMouse Bioconductor package.",
    "Data frame with the information of the DEGs in smoking human prenatal brain, generated by Semick SA, available in https://github.com/LieberInstitute/Smoking_DLPFC_Devel/blob/master/README.md",
    "Data frame with the information of the DEGs in smoking human adult brain, generated by Semick SA, available in https://github.com/LieberInstitute/Smoking_DLPFC_Devel/blob/master/README.md.",
    "Data frame with the information of the 208 samples."
  ),
  BiocVersion = "3.16",
  Genome = "GRCh38",
  SourceType = "GTF",
  SourceUrl = "https://bioconductor.org/packages/smokingMouse",
  SourceVersion = "Feb 28 2023",
  Species = "mus musculus",
  TaxonomyId = 10090,
  Coordinate_1_based = TRUE,
  DataProvider = "LIBD",
  Maintainer = "Daianna Gonzalez-Padilla <daianna2121@outlook.es>",
  RDataClass = c(
    "RangedSummarizedExperiment",
    "RangedSummarizedExperiment",
    "RangedSummarizedExperiment",
    "RangedSummarizedExperiment",
    "data.frame",
    "data.frame",
    "data.frame"
  ),
  DispatchClass = "Rdata",
  RDataPath = file.path(
    pkgname,
    outdir,
    c(
      "rse_gene_smoking_mouse_n208.Rdata",
      "rse_tx_smoking_mouse_n208.Rdata",
      "rse_jx_smoking_mouse_n208.Rdata",
      "rse_exon_smoking_mouse_n208.Rdata",
      "fetalGene.Rdata",
      "adultGene.Rdata",
      "Maternal_Smoking_pheno.txt"
    )
  ),
  Tags = "smokingMouse:LIBD:mouse",
  row.names = NULL,
  stringsAsFactors = FALSE
)

write.csv(
  meta,
  file = here::here("inst", "extdata", "metadata_smokingMouse.csv"),
  row.names = FALSE
)

## Check
if (FALSE) {
  AnnotationHubData::makeAnnotationHubMetadata(here::here(), fileName = "metadata_smokingMouse.csv")
}





## Reproducibility information
print("Reproducibility information:")
Sys.time()
proc.time()
options(width = 120)
session_info()

# setting  value
# version  R version 4.2.2 (2022-10-31)
# os       macOS Monterey 12.5.1
# system   aarch64, darwin20
# ui       RStudio
# language (EN)
# collate  en_US.UTF-8
# ctype    en_US.UTF-8
# tz       America/Mexico_City
# date     2023-02-28
# rstudio  2022.12.0+353 Elsbeth Geranium (desktop)
# pandoc   NA
